# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640f1878bf8e7c1871f483e478b6809fdd5841c085e0a81df55c1d3b6aca3a009fb8fec9bdc41a3ccc4a71389b89718148972c9b45bd3d195752601357a12667

test:
  secret_key_base: 0cc2f7d3ab9dca543f02db9410d7fd1b483e8db830a7ccae3638668d8f85eb0e451627bc79702715b2ee246b37585a9544d7013f8aebb639b633999512cadbb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
